export const ADD_DISH = "ADD_DISH";
export const REMOVE_DISH = "REMOVE_DISH";
export const SET_DISHINFORMATION = "SET_DISHINFORMATION"
export const SET_PRICE_DISHINFORMATION = "SET_PRICE_DISHINFORMATION"
export const SET_TEXT_DISHINFORMATION = "SET_DISH_TEXT_INFORMATION"
export const FETCHING_FAILED = "FETCHING_FAILED"
export const RESET_APP = "RESET_APP"